import { Mate, Pet } from './types';

export const MATES: Mate[] = [
  {
    id: '1',
    name: '田中 美咲',
    emoji: '🐕',
    imageUrl: '/mates/mate_1.png',
    bgGradient: 'from-emerald-200 to-teal-300',
    area: '世田谷区・三軒茶屋',
    city: '世田谷区',
    bio: '元獣医師アシスタントで、犬・猫の介護経験が10年以上あります。シニアペットの通院同伴や投薬補助が得意です。「預けるのが不安」という気持ち、よくわかります。一緒に大切なペットを支えさせてください。',
    services: [
      { type: 'walk', pricePerHour: 1800 },
      { type: 'hospital', pricePerHour: 2500 },
      { type: 'night', pricePerHour: 3200 },
    ],
    tags: ['🐕 犬OK', '🐈 猫OK', '💊 投薬OK', '🌙 深夜OK'],
    trustScore: {
      score: 87,
      completedCount: 32,
      repeatRate: 85,
      avgRating: 4.9,
      activeMonths: 12,
    },
    reviews: [
      {
        id: 'r1',
        ownerName: '佐藤 ゆり',
        ownerEmoji: '🐕',
        rating: 5,
        date: '2025年12月',
        comment: '老犬의 通院に毎月お願いしています。獣医さんとのやりとりもしっかりして下さり、帰宅後に詳しいレポートが届くので安心です。',
        repeatCount: 8,
      },
      {
        id: 'r2',
        ownerName: '中村 健一',
        ownerEmoji: '🐈',
        rating: 5,
        date: '2025年11月',
        comment: '出張が多いのでいつも美咲さんにおお願いしています。猫が最初は緊張していましたが、今では会うと嬉しそうにしています。',
        repeatCount: 15,
      },
      {
        id: 'r3',
        ownerName: '林 幸子',
        ownerEmoji: '🐕',
        rating: 5,
        date: '2025年10月',
        comment: '夜間の見守りをお願いしました。こまめに写真と報告を送ってくれて、安心して眠れました。',
        repeatCount: 3,
      },
    ],
    availableDates: [6, 7, 10, 12, 13, 14, 18, 19, 20, 21],
    repeatCount: 12,
  },
  {
    id: '2',
    name: '鈴木 陽介',
    emoji: '🐈',
    imageUrl: '/mates/mate_2.png',
    bgGradient: 'from-blue-200 to-indigo-300',
    area: '世田谷区・下北沢',
    city: '世田谷区',
    bio: '猫専門のケアが得意です。投薬補助・在宅ケアの経験が豊富で、ストレスをかけない接し方を大切にしています。猫ちゃんのペースに合わせて、ゆっくり信頼関係を築いていきます。',
    services: [
      { type: 'home_care', pricePerHour: 2200 },
      { type: 'night', pricePerHour: 3500 },
    ],
    tags: ['🐈 猫専門', '💊 投薬OK', '🌙 深夜OK', '🏥 医療ケア経験あり'],
    trustScore: {
      score: 94,
      completedCount: 48,
      repeatRate: 92,
      avgRating: 4.8,
      activeMonths: 18,
    },
    reviews: [
      {
        id: 'r4',
        ownerName: '木村 智子',
        ownerEmoji: '🐈',
        rating: 5,
        date: '2025年12月',
        comment: '慢性腎臓病の猫の在宅ケアをお願いしています。投薬も嫌がらずにやってもらえて本当に助かっています。',
        repeatCount: 20,
      },
      {
        id: 'r5',
        ownerName: '原田 昭',
        ownerEmoji: '🐈',
        rating: 5,
        date: '2025年11月',
        comment: '出張中に毎日来てもらいました。報告が丁寧で、猫の状態がよく分かって安心でした。',
        repeatCount: 6,
      },
    ],
    availableDates: [7, 8, 12, 14, 15, 17, 18, 21, 22, 25],
    repeatCount: 4,
  },
  {
    id: '3',
    name: '山田 花子',
    emoji: '🐕',
    imageUrl: '/mates/mate_3.png',
    bgGradient: 'from-orange-200 to-rose-300',
    area: '世田谷区・用賀',
    city: '世田谷区',
    bio: '大型犬2頭を飼っており、犬の行動学を学んでいます。散歩や在宅ケアが得意です。まずはお気軽にご相談ください！',
    services: [
      { type: 'walk', pricePerHour: 1500 },
      { type: 'home_care', pricePerHour: 1800 },
    ],
    tags: ['🐕 大型犬OK', '🐕 多頭OK', '🌱 丁寧な対応'],
    trustScore: {
      score: 72,
      completedCount: 8,
      repeatRate: 62,
      avgRating: 4.6,
      activeMonths: 3,
    },
    reviews: [
      {
        id: 'r6',
        ownerName: '斎藤 正',
        ownerEmoji: '🐕',
        rating: 5,
        date: '2026年1月',
        comment: '初めて利用しましたが、とても丁寧に対応していただきました。散歩後のレポートも可愛くて嬉しかったです。',
        repeatCount: 2,
      },
    ],
    availableDates: [8, 9, 10, 13, 14, 15, 16, 20, 21, 22],
    isNew: true,
  },
  {
    id: '4',
    name: '伊藤 恵子',
    emoji: '🐕',
    imageUrl: '/mates/mate_4.png',
    bgGradient: 'from-purple-200 to-pink-300',
    area: '渋谷区・恵比寿',
    city: '渋谷区',
    bio: 'ペットナース資格保有。高齢・要介護ペットの専門ケアが得意です。夜間の見守り・体位変換・流動食給餌まで対応しています。',
    services: [
      { type: 'home_care', pricePerHour: 2800 },
      { type: 'hospital', pricePerHour: 3000 },
      { type: 'night', pricePerHour: 4000 },
      { type: 'long_stay', pricePerHour: 2500 },
    ],
    tags: ['🏅 ペットナース資格', '🐕 介護専門', '💊 医療ケア', '🌙 24時間対応'],
    trustScore: {
      score: 96,
      completedCount: 67,
      repeatRate: 94,
      avgRating: 5.0,
      activeMonths: 24,
    },
    reviews: [
      {
        id: 'r7',
        ownerName: '渡辺 幸雄',
        ownerEmoji: '🐕',
        rating: 5,
        date: '2026年2月',
        comment: '末期がんの愛犬の介護をお願いしました。専門的な知識で最後まで丁寧にケアしていただき、感謝してもしきれません。',
        repeatCount: 30,
      },
    ],
    availableDates: [6, 8, 10, 12, 14, 16, 18, 20, 22],
  },
  {
    id: '5',
    name: '松本 直樹',
    emoji: '🐇',
    imageUrl: '/mates/mate_5.png',
    bgGradient: 'from-yellow-200 to-amber-300',
    area: '目黒区・中目黒',
    city: '目黒区',
    bio: '小動物・エキゾチックペット専門。うさぎ・ハムスター・鳥・爬虫類などのケア経験が豊富です。他のシッターでは断られてしまったペットの方もお気軽にご相談を！',
    services: [
      { type: 'home_care', pricePerHour: 2000 },
      { type: 'long_stay', pricePerHour: 1800 },
    ],
    tags: ['🐇 小動物OK', '🦜 鳥OK', '🦎 爬虫類OK', '🐹 ハムスターOK'],
    trustScore: {
      score: 81,
      completedCount: 22,
      repeatRate: 77,
      avgRating: 4.7,
      activeMonths: 8,
    },
    reviews: [
      {
        id: 'r8',
        ownerName: '小林 美奈',
        ownerEmoji: '🐇',
        rating: 5,
        date: '2025年12月',
        comment: 'うさぎを預けました。うさぎに詳しいシッターさんがなかなかいなくて困っていたので本当に助かりました。',
        repeatCount: 5,
      },
    ],
    availableDates: [9, 10, 11, 14, 15, 16, 19, 20, 21],
  },
];

export const MY_MATES = [MATES[0], MATES[1]];

export const PETS: Pet[] = [
  {
    id: 'p1',
    name: 'レオ',
    breed: '柴犬',
    category: 'dog',
    age: '3歳',
    gender: 'male',
    imageUrl: '/pets/leo.png',
    description: '元気いっぱいの柴犬です！お散歩が大好きで、他のワンちゃんとも仲良くできます。週に2回ほど、日中の散歩代行をお願いできる方を探しています。',
    area: '世田谷区・三軒茶屋',
    status: 'looking_for_mate',
  },
  {
    id: 'p2',
    name: 'モモ',
    breed: 'ゴールデンレトリバー',
    category: 'dog',
    age: '5歳',
    gender: 'female',
    imageUrl: '/pets/momo.png',
    description: 'おっとりした性格のゴールデンです。人が大好きで、誰にでもしっぽを振ります。平日の夕方にお散歩をお願いしたいです。',
    area: '世田谷区・用賀',
    status: 'looking_for_mate',
  },
  {
    id: 'p3',
    name: 'タマ',
    breed: '三毛猫',
    category: 'cat',
    age: '2歳',
    gender: 'female',
    imageUrl: '/pets/tama.png',
    description: '少し人見知りですが、慣れると甘えん坊です。出張中に1日1回のご飯とトイレの掃除をお願いできる方を探しています。',
    area: '渋谷区・恵比寿',
    status: 'looking_for_mate',
  },
  {
    id: 'p4',
    name: 'プク',
    breed: 'ミニウサギ',
    category: 'rabbit',
    age: '1歳',
    gender: 'male',
    imageUrl: '/pets/puku.png',
    description: '白くてふわふわのウサギです。人にかまってもらうのが大好き。週末の旅行中にお世話をお願いしたいです。',
    area: '目黒区・中目黒',
    status: 'booked',
  },
  {
    id: 'p5',
    name: 'タロウ',
    breed: 'フレンチブルドッグ',
    category: 'dog',
    age: '4歳',
    gender: 'male',
    imageUrl: '/pets/taro.png',
    description: 'おしゃれが好きなフレブルです！皮膚が少し弱いので、ケアに慣れている方だと嬉しいです。',
    area: '世田谷区・下北沢',
    status: 'looking_for_mate',
  },
];

export const RELATIONSHIP_TIMELINE = [
  { emoji: '🐾', text: '田中 美咲さんと12回目の散歩を完了', date: '2026年3月', color: 'bg-emerald-500' },
  { emoji: '⭐', text: '鈴木 陽介さんへの初めての投薬補助が完了', date: '2026年2月', color: 'bg-amber-500' },
  { emoji: '📈', text: '田中 美咲さんとの信頼スコアが 80 → 87 に上昇', date: '2025年12月', color: 'bg-blue-500' },
  { emoji: '🎉', text: '鈴木 陽介さんと初めてマッチング', date: '2025年11月', color: 'bg-purple-500' },
];
